/*
  Author: Runor Ewhro
  Description: Echoes that also appear in a phantom form, which the card reader
               matches as the same echo. Generated by
               scripts/assets/fetchPhantomEchoIcons.mjs; do not edit by hand.
*/

export const PHANTOM_ECHO_IDS: readonly string[] = [
  '390070076',
  '390070105',
  '390077024',
  '390080003',
  '390080007',
  '6000042',
  '6000043',
  '6000045',
  '6000051',
  '6000052',
  '6000053',
  '6000057',
  '6000058',
  '6000060',
  '6000067',
  '6000068',
  '6000071',
  '6000072',
  '6000073',
  '6000079',
  '6000080',
  '6000081',
  '6000082',
  '6000083',
  '6000090',
  '6000091',
  '6000104',
  '6000112',
  '6000121',
  '6000178',
  '6000179',
  '6000180',
  '6000190',
  '6000191',
  '6000194',
  '6000195',
  '6000196',
  '6000202',
  '6000214',
  '6000216',
  '6000217',
  '6000220',
]

export function getPhantomEchoIcon(id: string): string | null {
  return PHANTOM_ECHO_IDS.includes(id) ? `/assets/game/echoes/icons/phantom/${id}.webp` : null
}
